### ISSUE TITLE
enrichNCG - update the database

### ISSUE THREAD

**Issue by ABanaeiEsfahani** [YuLab-SMU/DOSE#33]
Hello,

The NCG data that you included in the package is quite old. Could you please update this? At the moment 2372 genes are existing in the database (http://ncg.kcl.ac.uk/) but your package has only 1571 genes. Thanks.

**Comment by GuangchuangYu** [comment]
@huerqiang pls update the data, including NCG and [DisGeNET](http://disgenet.org/).

**Comment by GuangchuangYu** [comment]
updated, <https://github.com/YuLab-SMU/DOSE/pull/36>.
