### ISSUE TITLE
Can I make similar ontology package using DOSE？

### ISSUE THREAD

**Issue by shangguandong1996** [YuLab-SMU/DOSE#38]
Hi, Dear developer

Disease Ontology is organized as a directed acyclic graph, just like other obo in http://www.obofoundry.org/. So I am wondering whether DOSE have a function that can produce another similar package in OBO?

Best wishes
Guandong Shang

**Comment by GuangchuangYu** [comment]
you want to derive another package using source code of DOSE?

**Comment by shangguandong1996** [comment]
Uncle Y, Actually I am wondering whether DOSE can make a function that parse the obo or owl, then I can use the enrich function to do enrichment analysis of XX_ontology :)

Please forgive me if it looks like ridiculous

Best wishes
Guandong Shang

**Comment by GuangchuangYu** [comment]
maybe there is such function in other package.

**Comment by shangguandong1996** [comment]
Thanks, Unlce Y, I get it :)
