### ISSUE TITLE
reproducibility of GSEA

### ISSUE THREAD

**Issue by vladpetyuk** [YuLab-SMU/DOSE#4]
GSEA relies on random permutations.  At the same time the function that implements GSEA uses `mclapply` for multithreaded computation. There is a need to make sure that permutations can be reproducible regardless the number of threads and OS.  A related StackOverflow [question](http://stackoverflow.com/questions/30610375/how-to-run-permutations-using-mclapply-in-a-reproducible-way-regardless-of-numbe) along with a solution.

**Comment by GuangchuangYu** [comment]
thanks for the [pull](https://github.com/GuangchuangYu/DOSE/pull/5).
