### ISSUE TITLE
gseGO through fgsea [ by GSEA_internal() ] is not fully reproducible, but is when running fgsea directly

### ISSUE THREAD

**Issue by guidohooiveld** [YuLab-SMU/DOSE#45]
Hi,
I am struggling a bit with the reproducibility of the results of a GSEA run through `clusterProfiler`/`DOSE` using identical input, in my particular case the function `gseGO()`.
I noticed this while sharing some code with a colleague, who (using the same data) got very similar, but not identical results compared to the results I got. I decided to have a closer look at this.

When checking the code on Github, I noticed that in the end the `clusterProfiler` calls the function` GSEA_internal()` (see [here](https://github.com/YuLab-SMU/clusterProfiler/blob/e1959b42e3e9f82ad84984326b3f8f7657e99d21/R/gseAnalyzer.R#L23) and [here](https://github.com/YuLab-SMU/clusterProfiler/blob/e1959b42e3e9f82ad84984326b3f8f7657e99d21/R/gseAnalyzer.R#L43])), which in turn 'lives' in `DOSE`. Hence this post at the `DOSE` Github repository.

The function `GSEA_internal()` is defined [here](https://github.com/YuLab-SMU/DOSE/blob/5b25216d9d13020ad336813b59e57fb3206c468b/R/gsea.R#L148), and by default `fgsea()` is called to perform GSEA (see [here](https://github.com/YuLab-SMU/DOSE/blob/5b25216d9d13020ad336813b59e57fb3206c468b/R/gsea.R#L164)) using the function `GSEA_fgsea`. `GSEA_fgsea` is defined [here](https://github.com/YuLab-SMU/DOSE/blob/5b25216d9d13020ad336813b59e57fb3206c468b/R/gsea.R#L2).

My code to generate the GSEA results (using the included sample data):
```
> library(clusterProfiler)
> library(org.Hs.eg.db)
> 
> data(geneList, package="DOSE")
> 
> run1 <- gseGO(geneList     = geneList,
+               OrgDb        = org.Hs.eg.db,
+               ont          = "MF",
+               eps          = 0.0,
+               minGSSize    = 100,
+               maxGSSize    = 500,
+               pAdjustMethod= "none",
+               pvalueCutoff = 1,
+               verbose      = FALSE)
> 
> run2 <- gseGO(geneList     = geneList,
+               OrgDb        = org.Hs.eg.db,
+               ont          = "MF",
+               eps          = 0.0,
+               minGSSize    = 100,
+               maxGSSize    = 500,
+               pAdjustMethod= "none",
+               pvalueCutoff = 1,
+               verbose      = FALSE)
> 
```

To check reproducibility I plot the p-values of the 2 runs against each other.
When fully reproducible, I would expect I sharp diagonal line (because x should be equal to y). However, this is not the case.
Code and picture:
```
> merged.res <- merge( as.data.frame(run1), as.data.frame(run2), by.x="ID", by.y="ID")
> plot(  merged.res$pvalue.x, merged.res$pvalue.y )
> 
```
![image](https://user-images.githubusercontent.com/22979991/96008485-e6a16f00-0e3f-11eb-82e9-88fb917ec25a.png)

In the `fgsea` [vignette](https://www.bioconductor.org/packages/release/bioc/vignettes/fgsea/inst/doc/fgsea-tutorial.html) I noticed that to fully achieve reproducibility, a seed value should be explicitly set. I also noticed that `GSEA_internal()` indeed accepts an argument `seed` (default = `FALSE`). However, setting `seed=TRUE` did NOT make the results fully reproducible... (no x=y diagonal).
```

> set.seed(1234)
> 
> run3 <- gseGO(geneList     = geneList,
+               OrgDb        = org.Hs.eg.db,
+               ont          = "MF",
+               eps          = 0.0,
+               minGSSize    = 100,
+               maxGSSize    = 500,
+               pAdjustMethod = "none",
+               seed         = TRUE,
+               pvalueCutoff = 1,
+               verbose      = FALSE)
> 
> run4 <- gseGO(geneList     = geneList,
+               OrgDb        = org.Hs.eg.db,
+               ont          = "MF",
+               eps          = 0.0,
+               minGSSize    = 100,
+               maxGSSize    = 500,
+               pAdjustMethod = "none",
+               seed         = TRUE,
+               pvalueCutoff = 1,
+               verbose      = FALSE)
> 
> 
> merged.res.seed <- merge( as.data.frame(run3), as.data.frame(run4), by.x="ID", by.y="ID")
> 
> plot( merged.res.seed$pvalue.x, merged.res.seed$pvalue.y )
> 
```
![image](https://user-images.githubusercontent.com/22979991/96009117-8f4fce80-0e40-11eb-886f-cb8b62f81f6e.png)

To confirm `fgsea` is able produce identical results, I ran `fgsea()` directly; when setting a seed value I indeed got fully reproducible results! Note: for convenience I used the sample data set included with `fgsea` to illustrate my point; moreover, if a seed values is not explicitly set the results from `fgsea` are also NOT fully reproducible (results not shown).
```
> library(fgsea)
> data(examplePathways)
> data(exampleRanks)
> 
> set.seed(1234)
> fgseaRes3 <- fgsea(examplePathways, exampleRanks, maxSize=500, eps=0)
> fgseaRes4 <- fgsea(examplePathways, exampleRanks, maxSize=500, eps=0)
> 
> merged.res.fgsea.seed <- merge( fgseaRes3, fgseaRes3, by.x="pathway", by.y="pathway")
> plot(  merged.res.fgsea.seed$pval.x, merged.res.fgsea.seed$pval.y )
>
``` 
![image](https://user-images.githubusercontent.com/22979991/96009497-01281800-0e41-11eb-9dfc-9c858bdf709b.png)

Now my question:
How to call `gseGO()` (or `gseKEGG()`, or any other function that relies on `GSEA_internal()` ) to reproduce results? Should be something changed in the code (or arguments) of `GSEA_internal()`? Also because `fgsea()` itself may have been changed as well the last couple of months?

In addition, while looking through the code of `GSEA_internal()` I noticed that an argument called `exponent` is used, whereas the corresponding argument in `fgsea()` is (now) called `gseaParam` (and not `seed`); also good to correct this?

<<edit 5 days later>>
Ignore last comment directly above, because in `GSEA_fgsea` the value of the argument `gseaParam` is correctly defined by `exponent`. 
So the remaining question is how to reproduce results.
<</edit>>

Thanks,
Guido

**Comment by guidohooiveld** [comment]
```
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)

Matrix products: default

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
[1] fgsea_1.14.0           org.Hs.eg.db_3.11.4    AnnotationDbi_1.50.3  
[4] IRanges_2.22.2         S4Vectors_0.26.1       Biobase_2.48.0        
[7] BiocGenerics_0.34.0    clusterProfiler_3.16.1

loaded via a namespace (and not attached):
 [1] viridis_0.5.1       httr_1.4.2          tidyr_1.1.2        
 [4] tidygraph_1.2.0     bit64_4.0.5         jsonlite_1.7.1     
 [7] viridisLite_0.3.0   splines_4.0.2       ggraph_2.0.3       
[10] DO.db_2.9           BiocManager_1.30.10 rvcheck_0.1.8      
[13] triebeard_0.3.0     urltools_1.7.3      blob_1.2.1         
[16] progress_1.2.2      ggrepel_0.8.2       pillar_1.4.6       
[19] RSQLite_2.2.1       lattice_0.20-41     glue_1.4.2         
[22] downloader_0.4      digest_0.6.25       RColorBrewer_1.1-2 
[25] polyclip_1.10-0     qvalue_2.20.0       colorspace_1.4-1   
[28] cowplot_1.1.0       Matrix_1.2-18       plyr_1.8.6         
[31] pkgconfig_2.0.3     purrr_0.3.4         GO.db_3.11.4       
[34] snow_0.4-3          scales_1.1.1        ggplotify_0.0.5    
[37] europepmc_0.4       tweenr_1.0.1        enrichplot_1.8.1   
[40] BiocParallel_1.22.0 ggforce_0.3.2       tibble_3.0.3       
[43] generics_0.0.2      farver_2.0.3        ggplot2_3.3.2      
[46] ellipsis_0.3.1      magrittr_1.5        crayon_1.3.4       
[49] memoise_1.1.0       DOSE_3.14.0         MASS_7.3-53        
[52] xml2_1.3.2          tools_4.0.2         data.table_1.13.0  
[55] prettyunits_1.1.1   hms_0.5.3           lifecycle_0.2.0    
[58] stringr_1.4.0       munsell_0.5.0       compiler_4.0.2     
[61] gridGraphics_0.5-0  rlang_0.4.7         ggridges_0.5.2     
[64] grid_4.0.2          igraph_1.2.6        gtable_0.3.0       
[67] DBI_1.1.0           reshape2_1.4.4      graphlayouts_0.7.0 
[70] R6_2.4.1            gridExtra_2.3       dplyr_1.0.2        
[73] bit_4.0.4           fastmatch_1.1-0     GOSemSim_2.14.2    
[76] stringi_1.5.3       Rcpp_1.0.5          vctrs_0.3.4        
[79] scatterpie_0.1.5    tidyselect_1.1.0   
> 

```

**Comment by GuangchuangYu** [comment]
```r
  set.seed(1234)
  run1 <- gseDO(geneList     = geneList,


                eps          = 0.0,
                minGSSize    = 100,
                maxGSSize    = 500,
                pAdjustMethod= "none",
                pvalueCutoff = 1,
                seed =TRUE,
                verbose      = FALSE)
  
  run2 <- gseDO(geneList     = geneList,


                eps          = 0.0,
                minGSSize    = 100,
                maxGSSize    = 500,
                pAdjustMethod= "none",
                pvalueCutoff = 1,
                seed =TRUE,
                verbose      = FALSE)

merged.res.seed <- merge( as.data.frame(run1), as.data.frame(run2), by.x="ID", by.y="ID")
plot( merged.res.seed$pvalue.x, merged.res.seed$pvalue.y )

```

Using `seed = TRUE` should works.
