### ISSUE TITLE
How does showCategory function work?

### ISSUE THREAD

**Issue by smk5g5** [YuLab-SMU/DOSE#54]
I have run GSEA analysis on multiple msigdb categories. I see that the dotplot function does not work with msigdb data or with GSEA. 

For my data I ran GSEA on GO BP first for each cluster and then simplified the resulting gsea list of lists like this and then merged the results. 

```
gse_list_byclus_simp <- lapply(gse_list_byclus, simplify)
#merge gsea results
gsea_merged_results <- simplify(merge_result(gse_list_byclus_simp))
```
Then I calculated the gene count variable and added it to the gsea merged result compare cluster object.
```
#calculate gene_count for merged gsea
gene_count<- gsea_merged_results@compareClusterResult %>% group_by(ID) %>% summarise(count = sum(str_count(core_enrichment, "/")) + 1)
gsea_merged_results@compareClusterResult<- left_join(gsea_merged_results@compareClusterResult, gene_count, by = "ID") %>% mutate(GeneRatio = count/setSize)
````
Now when I run 
```
test <- dotplot(gsea_merged_results, showCategory=12)
```
I keep getting this error I don't know why?
```
Error in `$<-.data.frame`(`*tmp*`, "Cluster", value = NA_integer_) :
  replacement has 1 row, data has 0
```
So I wanted to look at the logic of showCategory function but I can't seem to find the code in your github r directory.
I think the includeall=T parameter in dotplot actually selects the unique terms by cluster/condition from all and sort by significance (here I think it is adj. p-value) but If I do select the terms using something like a function below (where cat_df is concatenated dataframe with gsea enrichment from each cluster and number_cat is the number of terms to select and group_var here is 'Cluster' and sort_var adj. p-value but if I select that way I get GO terms from the data that are not informative and are probably present at higher levels e.g. "biological regulation", "response to stimulus" etc

```
top_n_categories_includeall <- function(cat_df,number_cat,group_var,sort_var){
  topn_cats_byclus <- cat_df %>%
    group_by(group_var) %>%
    arrange(sort_var) %>%
    slice(1:number_cat)
sel_cats <- unique(topn_cats_byclus$Description)
sel_catdf <- cat_df[cat_df$Description %in% sel_cats,]
return(sel_catdf)
}
```
So my question is two fold is there a way to make compare cluster work on GSEA data or if I can visualize the selected categories using dotplot. Also in order to extend dotplot for myself to use it with different msigdb annotations I need to know how is  showCategory working in the background.

Thanks!

**Comment by huerqiang** [comment]
@smk5g5 
1. "for each cluster" : Maybe you should use `enrichGO` instead of `gseGO`.
2. The `merge_result` function is designed to be used in list of enrichResult(the output of `enrichGO`), not gseaResult(the output of `gseGO`) . 
3. To use `dotplot`, you should hava a `Count` column，not `count`.

If you have more questions, please provide the data and repeatable code.

**Comment by GuangchuangYu** [comment]
use dplyr verbs implemented in clusterProfiler, https://yulab-smu.top/biomedical-knowledge-mining-book/clusterProfiler-dplyr.html

If what you want is not supported, open an issue for feature request. 

Don't use `@` to manipulate data yourself. Otherwise, we can't guarantee anything.
