### ISSUE TITLE
Error installing latest version of DOSE

### ISSUE THREAD

**Issue by archanabhardwaj** [YuLab-SMU/DOSE#69]
Hello
I am getting error while running gseGO for my multiple geneList under compareCluster function. I am getting same error as given https://github.com/YuLab-SMU/clusterProfiler/issues/409. As a solution, I tried to install the latest Github version of DOSE 

>install.packages("remotes")
>remotes::install_github("YuLab-SMU/DOSE")

But it gives me error : 

ERROR: dependency ‘HDO.db’ is not available for package ‘DOSE’
* removing ‘/home/archana/miniconda3/envs/seurat/lib/R/library/DOSE’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmpYLXFMf/file1e1f6b2ce4dc/DOSE_3.23.3.tar.gz’ had non-zero exit status

Please help me to fix this issue. 
Thanks in advance

**Comment by GuangchuangYu** [comment]
remotes::install_github("yulab-smu/HDO.db")
