### ISSUE TITLE
cnetplot for selected gene and GO term

### ISSUE THREAD

**Issue by antoine4ucsd** [YuLab-SMU/DOSE#70]
Hello
First of all, thank you for sharing this impressive package.
I have a question/request regarding the cnetplot function.  I would like to use it to plot a'network' of genes associated with specific GO cancer terms or hallmarks.
I am attaching an example of data which include pid, ENTREZID, GO term, Hallmarks
For example, I would like to plot the cnet of all genes by hallmarks or within a given hallmark, all genes and `term names`
I did some enrichment analyses too but my goal here is just to be descriptive.
Does that make sense?
is there a way to adapt this dataframe to use it as an input for cnetplot?
[mydata.csv](https://github.com/YuLab-SMU/DOSE/files/9995589/mydata.csv)

thank you in advance!

**Comment by GuangchuangYu** [comment]
see <https://yulab-smu.top/biomedical-knowledge-mining-book/enrichplot.html#cnetplot>
