### ISSUE TITLE
MPO.db/HPO.db installation error

### ISSUE THREAD

**Issue by ushione** [YuLab-SMU/DOSE#79]
Hello, Professor Yu. Recently, I have been using R version 4.3.1 in a Linux environment (a server). However, I encountered problems during the installation of the MPO.db and HPO.db packages, which further prevented me from installing the latest version of DOSE. As a result, I am unable to use clusterProfiler. The screenshot below shows the error during the installation of MPO.db:

![MPO](https://github.com/YuLab-SMU/DOSE/assets/87009163/fbb82a28-a45e-4faf-a596-219b9ede216a)

I have had the privilege of using your DOSE package, with the previous version being 3.26.2. I have also carefully read your update documentation (https://github.com/YuLab-SMU/DOSE/blob/devel/NEWS.md) and learned that **DOSE (after 3.27.2) began to use the “MPO.db” and “HPO.db” packages**. As you know, as mentioned in the previous issue, installing these two packages locally did not solve my problem (mainly due to network issues preventing the verification of package installation). Here is a failed attempt at local installation:

![myTry](https://github.com/YuLab-SMU/DOSE/assets/87009163/ef2f8bb8-3b51-4b07-a5b5-12bb27e5193b)

I am currently unable to resolve this network issue, so ** I hope to skip the installation of these two packages by installing DOSE version 3.26**, in order to ensure the basic use of clusterProfiler. However, I cannot find a DOSE version like 3.26 on Bioconductor (https://bioconductor.org/help/search/index.html). Therefore, **I would like to reach out to you to obtain resources for the old version of DOSE (such as ver. 3.26.2)**.

Of course, I am also very much looking forward to any other feasible solutions you may propose.

Thank you for taking the time to address my issue, and once again, I sincerely express my gratitude for the toolkits you have provided.

--------------------------------------------------------------------------------------------
In chinese:

余老师您好。我最近在Linux环境中（一台服务器）使用4.3.1R，但在MPO.db和HPO.db两个包的安装过程中遇到了问题，因此进一步导致最新的DOSE无法安装，最终使得我无法使用clusterProfiler。安装MPO.db报错的截图为以上第一张图。

我曾有幸使用过您写的DOSE，其原先的版本为3.26.2。我也仔细阅读了您的更新文档，得知了【3.27.2版本之后的DOSE开始使用“MPO.db”和“HPO.db”这两个包】。正如您所知道的那样，上一个Issues中提到的本地安装这个两个包并不能解决我的问题（主要是网络问题使得无法验证这个包的安装？）。我本地安装的失败尝试为以上第二张图。

我暂时无法解决这个网络问题，因此**我希望通过安装3.26的DOSE来跳过这两个包的安装，以保障clusterProfiler的基本使用**。但我无法在bioconductor（https://bioconductor.org/help/search/index.html）获得像3.26这样的DOSE版本。**因此我希望向您联系获得旧版DOSE的资源（比如曾经的3.26.2版本）**。

当然，我也非常期待您提出其他可行的解决方案~

感谢您百忙之中处理我的issue，再次由衷地向您提供的工具包表达感谢。

**Comment by huerqiang** [comment]
@ushione Please see https://github.com/YuLab-SMU/DOSE/wiki/The-solution-to-the-failure-of-installing-MPO.db-and-HPO.db-packages

**Comment by ushione** [comment]
@huerqiang Thank you for your prompt response. I will check as soon as possible whether these plans are effective for me.

In addition, **I would like to know if I can obtain a previous version of DOSE (such as 3.26.2?)**, which may be the quickest solution. Or for what reason is it highly recommended not to use versions like 3.26? (If that's the case, I'm sorry I may not have found such a prompt in the update log)

**Comment by GuangchuangYu** [comment]
Now we move the MPO.db and HPO.db to `Suggests` and there is no need to install these two packages prior to the installation of DOSE.

see also <https://mp.weixin.qq.com/s/lsQhNRub9rWjw0H_BkLGmA>.
