### ISSUE TITLE
GSEA to discover mixed enriched terms

### ISSUE THREAD

**Issue by mauritsunkel** [YuLab-SMU/DOSE#84]
Hi,

Now, enriched terms are either up- or down regulated, likely because of the weighting in the running sum implementation. However, there must be terms with mixed enrichment, where some type of mixed activation/inhibition actually leads to very enriched terms, which is now missed through the implementation. I realise this is more in the domain of topology based algorithms, applied to terms which represent pathways, however, I'm hopeful we could get some additional information out of just the ranked expression list.

In order to find mixed enriched terms, I'm curious if it would be proper, and statistically viable, to make the expression values absolute before running GSEA? 
Or would additional transformations like scaling/normalization be needed additionally? 

Best,
Maus

**Comment by guidohooiveld** [comment]
For the archive: this issue has been cross-posted/discussed at the GitHub of `fgsea`: https://github.com/ctlab/fgsea/issues/154
